version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
      - ./users.db:/app/users.db
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend